server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/shopapp"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: shopapp
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  signerKey: "ArTg26yJe5nSb09iXcyeNQrpNcOUTIiz3zQKIxaCXftlvKsBTKlW3fI65yCXsYGy"
  valid-duration: 3600 # in second
  refresh-duration: 36000 # in seconds